trigger:
- master

pool:
  vmImage: 'win1803'

stages:
- stage:
  jobs:
  - job:
    steps:
    - task: Docker@2
      inputs:
        repository: 'weather-reporter'
        command: 'build'
        Dockerfile: '**/Dockerfile'
- stage:
  jobs:
  - job:
    container:
      image: 'weather-reporter'
    steps:
      - script: conda
        displayName: 'run anaconda'


