trigger:
- master

pool:
  vmImage: 'win1803'

container:
  image: 'fmcclean/anaconda-windows:weather-reporter'
  endpoint: 'Docker Registry'


variables:
  version: v0.1.0

steps:

- script: python -m unittest tests/test_layout.py
  displayName: 'run test_layout.py'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'tests/outputs/temp_out.pdf'
    artifactName: 'temp_out.pdf'

- script: python -m PyInstaller -y build.spec $(version)
  displayName: 'Build exe'

- task: GitHubRelease@0
  displayName: ‘Edit GitHub Release’
  inputs:
    gitHubConnection: fmcclean
    repositoryName: fmcclean/weather-reporter
    action: edit
    tag: $(version)
    assets: dist/*
    isDraft: true
