trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'

steps:

- powershell: |
    $version = git describe --tags
    Write-Host "##vso[task.setvariable variable=version]$version"
    git describe
  displayName: Get version number from git


- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: pip install -r requirements.txt
  displayName: Install packages from requirements

- script: python -m unittest -f tests/test_app.py
  displayName: Test App

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'tests/outputs/output.pdf'
    artifactName: 'output.pdf'

- script: python -m PyInstaller -y build.spec
  displayName: Build exe

- task: GitHubRelease@0
  displayName: Create GitHub Release
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  inputs:
    gitHubConnection: github/fmcclean
    repositoryName: fmcclean/weather-reporter
    action: edit
    releaseNotesFile: docs/release_notes/$(version).md
    tag: $(version)
    assets: dist/*
    isDraft: false
    isPreRelease: false
    title: SHEAR Weather Reporter $(version)
