trigger:
- master

pool:
  vmImage: 'win1803'

stages:
- stage:
  steps:
  - task: Docker@2
    inputs:
      repository: 'weather-reporter'
      command: 'build'
      Dockerfile: '**/Dockerfile'
- stage:
  container:
    image: 'weather-reporter'
  steps:
    - script: conda
      displayName: 'run anaconda'


