trigger:
- master

pool:
  vmImage: 'win1803'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Registry'
    repository: 'anaconda-windows'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'weather-reporter-$(Build.BuildId)'
