trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- script: |
    echo "##vso[task.setvariable variable=version]git describe"
    echo $(version)
  displayName: Get version number from git

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH

- script: conda env update --quiet -f environment.yml -n base
  displayName: Install packages from environment.yml

- script: |
    call activate
    python -m unittest tests/test_layout.py
  displayName: Test layout.py

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'tests/outputs/temp_out.pdf'
    artifactName: 'temp_out.pdf'

- script: |
    call activate
    python -m PyInstaller -y build.spec
  displayName: Build exe

- task: GitHubRelease@0
  displayName: ‘Create GitHub Release’
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  inputs:
    gitHubConnection: github/fmcclean
    repositoryName: fmcclean/weather-reporter
    action: create
    tagSource: Git tag
    releaseNotesFile: docs/release_notes/$(version).md
    assets: dist/*
    isPreRelease: true
    title: Shetran Results Viewer $(version)
