trigger:
- master

pool:
  vmImage: 'win1803'

container:
  image: 'fmcclean/anaconda-windows:weather-reporter'
  endpoint: 'Docker Registry'

steps:

- script: python -m unittest tests/test_main.py
  displayName: 'run test_main.py'


