trigger:
- master

pool:
  vmImage: 'windows-latest'
#
#container:
#  image: 'fmcclean/anaconda-windows:weather-reporter'
#  endpoint: 'Docker Registry'

variables:
  version: v0.1.0

steps:

- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
  displayName: Add conda to PATH

- script: conda env update --quiet -f environment.yml -n base
  displayName: Install packages from environment.yml

- script: |
    call activate
    python -m unittest tests/test_layout.py
  displayName: Test layout.py

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'tests/outputs/temp_out.pdf'
    artifactName: 'temp_out.pdf'

- script: |
    call activate
    python -m PyInstaller -y build.spec $(version)
  displayName: Build exe

- script: |
    git push origin :refs/tags/$(version)
    git tag -fa $(version)
    git push origin master --tags
  displayName: Update tag based on version number

- task: GitHubRelease@0
  displayName: ‘Edit GitHub Release’
  inputs:
    gitHubConnection: github/fmcclean
    repositoryName: fmcclean/weather-reporter
    action: edit
    tag: $(version)
    assets: dist/*
    isDraft: true
    title: Shetran Results Viewer $(version)
