version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'
      - run:
          name: Download and install Miniconda
          command: |
            (New-Object System.Net.WebClient).DownloadFile('https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe', 'Anaconda3.exe')
            Unblock-File Anaconda3.exe
            .\Anaconda3.exe /InstallationType=JustMe /RegisterPython=1 /S /D=%UserProfile%\Anaconda3
            Set PATH=%PATH%;%UserProfile%\Anaconda3;%UserProfile%\Anaconda3\Scripts;%UserProfile%\Anaconda3\Library\bin
            conda env create -f environment.yml
            conda activate myenv
            python main.py

